version: 0.2

phases:
  install:
    commands:
      echo install
  pre_build:
    commands:
      echo pre_build
  build:
    commands:
      echo build
      echo $AWS_DEFAULT_REGION
      echo $AWS_REGION
      echo $CODEBUILD_BUILD_ARN
      echo $CODEBUILD_BUILD_ID
      echo $CODEBUILD_BUILD_IMAGE
      echo $CODEBUILD_BUILD_SUCCEEDING
      echo $CODEBUILD_INITIATOR
      echo $CODEBUILD_KMS_KEY_ID
      echo $CODEBUILD_LOG_PATH
      echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      echo $CODEBUILD_SOURCE_REPO_URL
      echo $CODEBUILD_SOURCE_VERSION
      echo $CODEBUILD_SRC_DIR
      echo $CODEBUILD_START_TIME
      echo $CODEBUILD_WEBHOOK_TRIGGER
      echo $HOME
  post_build:
    commands:
      echo post_build